config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

   resources :posts, only: [] do
 # #5
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
  # #7
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :questions

  post 'users/confirm' => 'users#confirm'
  get "Topics" => 'welcome#topics'
  get 'about' => 'welcome#about'
  get "/welcome/faq" => "welcome#faq"
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

     validates :body, length: { minimum: 5 }, presence: true
     validates :user, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true


  def up_votes
    # #9
    votes.where(value: 1).count
  end

  def down_votes
    # #10
    votes.where(value: -1).count
  end

  def points
    # #11
    votes.sum(:value)
  end
  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
has_many :posts, dependent: :destroy
 def self.search(search)
 where("title LIKE ?", "%#{search}%")
end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # #2
  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :member }

  # #3
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  # #4

  validates :password, length: { minimum: 6 }, allow_blank: true
  # #5
  validates :email,
  presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 254 }

  # #6
  has_secure_password
  enum role: [:member, :admin]
  def favorite_for(post)
     favorites.where(post_id: post.id).first
   end
   def avatar_url(size)
       gravatar_id = Digest::MD5::hexdigest(self.email).downcase
       "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
     end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post
  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
    before_action :authenticate
    def show
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_sign_in, except: :show

  # #10
  before_action :authorize_user, except: [:show, :new, :create]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end


  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user

    if @post.save
      # #11
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      # #12
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end
  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      redirect_to [@post.topic, @post]
    end
  end
  def destroy
    @post = Post.find(params[:id])

    # #8
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end


  def edit
    @post = Post.find(params[:id])
  end
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
  def authorize_user
    post = Post.find(params[:id])
# #11
    unless current_user == post.user || current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to [post.topic, post]
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # #7
  before_action :require_sign_in, except: [:index, :show]
# #8

  def edit
    @topic = Topic.find(params[:id])
  end

  def index
    @topics = Topic.all
  end
  def update
    @topic = Topic.find(params[:id])

    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end
  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end
  def destroy
     @topic = Topic.find(params[:id])

     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
   end
   private
   def topic_params
     params.require(:topic).permit(:name, :description, :public)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
       @user = User.new
     end

     def create
   # #9
       @user = User.new
       @user.name = params[:user][:name]
       @user.email = params[:user][:email]
       @user.password = params[:user][:password]
       @user.password_confirmation = params[:user][:password_confirmation]

   # #10
       if @user.save
         flash[:notice] = "Welcome to Bloccit #{@user.name}!"
         create_session(@user)
         redirect_to root_path
       else
         flash.now[:alert] = "There was an error creating your account. Please try again."
         render :new
       end
     end
     def show
      @user = User.find(params[:id])
      @posts = @user.posts.visible_to(current_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # #4
    def form_group_tag(errors, &block)
      css_class = 'form-group'
      css_class << ' has-error' if errors.any?
 # #5
      content_tag :div, capture(&block), class: css_class
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
        current_user && (current_user == comment.user || current_user.admin?)
     end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
          current_user && (current_user == post.user || current_user.admin?)
     end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
       session[:user_id] = user.id
     end

   # #5
     def destroy_session(user)
       session[:user_id] = nil
     end

   # #6
     def current_user
       User.find_by(id: session[:user_id])
     end
end

app/helpers/topics_helper.rb
module TopicsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/topics/_topic.html.erb
<center>
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
<!-- #8 -->
      <%= link_to topic.name, topic %>
    </h4>
    <small>
      <%= topic.description %>
    </small>
  </div>
</div>
</center>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
 <!-- #11 -->
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/index.html.erb
<center>
<h1>Topics</h1>
<div class="col-md-4">
<!-- #9 -->
  <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
</div>
 <div class="row">
   <div class="col-md-8">
 <!-- #7 -->
     <% @topics.each do |topic| %>
      <%= render partial: 'topic', locals: { topic: topic } %>
     <% end %>
   </div>
   <!-- #12 -->

 </div>
</center>

app/views/topics/new.html.erb
<h1>New Topic</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
<center>

<h1><%= @topic.name %></h1>
<%= form_tag(topics_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Topics" %>
<%= submit_tag "Search" %>

<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>

<% end %>
<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= auto_link @topic.description, html: { target: '_blank' }%></p>
    <!-- #10 -->
    <% @topic.posts.each do |post| %>
    <div class="media">
      <%= render partial: 'votes/voting', locals: { post: post } %>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to post.title, topic_post_path(@topic, post) %>
        </h4>
        <small>
          submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
          <%= post.comments.count %> Comments
        </small>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
    <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
  </div>
</div>
</center>