config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

   resources :posts, only: [] do
 # #5
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end
  # #7
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :questions

  post 'users/confirm' => 'users#confirm'
  get "Topics" => 'welcome#topics'
  get 'about' => 'welcome#about'
  get "/welcome/faq" => "welcome#faq"
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

     validates :body, length: { minimum: 5 }, presence: true
     validates :user, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true


  def up_votes
    # #9
    votes.where(value: 1).count
  end

  def down_votes
    # #10
    votes.where(value: -1).count
  end

  def points
    # #11
    votes.sum(:value)
  end
  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
has_many :posts, dependent: :destroy
 def self.search(search)
 where("title LIKE ?", "%#{search}%")
end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # #2
  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :member }

  # #3
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  # #4

  validates :password, length: { minimum: 6 }, allow_blank: true
  # #5
  validates :email,
  presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 254 }

  # #6
  has_secure_password
  enum role: [:member, :admin]
  def favorite_for(post)
     favorites.where(post_id: post.id).first
   end
   def avatar_url(size)
       gravatar_id = Digest::MD5::hexdigest(self.email).downcase
       "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
     end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post
  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
    before_action :authenticate
    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # #4
    def form_group_tag(errors, &block)
      css_class = 'form-group'
      css_class << ' has-error' if errors.any?
 # #5
      content_tag :div, capture(&block), class: css_class
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
        current_user && (current_user == comment.user || current_user.admin?)
     end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
          current_user && (current_user == post.user || current_user.admin?)
     end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
       session[:user_id] = user.id
     end

   # #5
     def destroy_session(user)
       session[:user_id] = nil
     end

   # #6
     def current_user
       User.find_by(id: session[:user_id])
     end
end

app/helpers/topics_helper.rb
module TopicsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head >
  <title>Scratch</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">

</head>
<center>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <% if current_user %>
      <li class="pull-right"><%= link_to "Sign Out", session_path(current_user), method: :delete %></li>

      <li class="pull-right"><%= image_tag current_user.avatar_url(48) %></li>
      <li class="pull-right"><%= link_to current_user.name, user_path(current_user) %></li>
    </div>
    <% else %>
    <li class="pull-right"><%= link_to "Sign In", new_session_path %></li>
    <li class="pull-right"><%= link_to "Sign Up", new_user_path %></li>
    <% end %>

  </ul>



  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
  <% end %>



  <%= yield %>

  <!-- Signup Section -->
  <section id="signup" class="signup-section">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 mx-auto text-center">

          <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
          <h2 class="text-white mb-5">Subscribe to receive updates!</h2>

          <form class="form-inline d-flex">
            <input type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" placeholder="Enter email address...">
            <button type="submit" class="btn btn-primary mx-auto">Subscribe</button>
          </form>

        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-black small text-center text-white-50">
    <div class="container">
      Copyright &copy; Dj Scratch Trax 2018
    </div>
  </footer>
</div>
</body>
</center>
</html>